version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: bd-contenedor
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./schemas:/var/lib/mysql